# After the file is generated by codeVis, run this file to merge all instances into a total instance for training.
import os

# Create a file under the txt folder, save the path, save the label
root_path_csvs = '../data/csvs/'
root_path_img = '../data/img/'
gray_paths = ['/gray_img/']

for csv_file in os.listdir(root_path_csvs):
    # Get the project name from source projects
    project_name = os.path.splitext(csv_file)[0]
    print(project_name + " begin!")

    # Get the path of the target folder
    save_file_path = root_path_img + project_name + '/instances.txt'
    # open the file, create it if not
    save_file = open(save_file_path, 'w')

    # Merge all instance.txt into one instance.txt for index training
    for channel_path in gray_paths:
        channel_instance_file_path = root_path_img + project_name + channel_path + 'instances.txt'

        # Traverse a single file, read the number of lines
        for line in open(channel_instance_file_path):
            save_file.writelines(line)

    # close file
    save_file.close()

    print(project_name + " done!")